version: 2
updates:
  - package-ecosystem: "pypi"
    directory: "/"
    # needed to update requirements.txt
    allow:
      - dependency-type: all
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
